### ISSUE TITLE
Cannot connect to a websocket hosted in aws api gateway

### ISSUE THREAD

**Issue by swiftmarine** [yai333/React-Chat-App-using-AWS-API-Gateway-Websocket-and-Serverless-Framework#7]
When i enter the following command in the cmd the connection is ok and the connection id is saved in a dynamo db table:::::::::
wscat -c wss://xxxxxxx.execute-api.eu-west-1.amazonaws.com/dev -H Auth:tESTtestTestxxxxYYYYZZZyyyyxxJKKKKKJ

Inside the react chat window component i am replacing the actual deployed wss endpoint like this 
but i get from the debug in the browser ::::

WebSocket connection to 'wss://xxxx.execute-api.eu-west-1.amazonaws.com/dev' failed: HTTP Authentication failed; no valid credentials available

What am i doing wrong?
Notice that i have a custom authorizer function that get the Auth header value and make a call to my node backend to validate the caller and then the connection is established only with wscat.
Do you have any idea what is going on? 

Please help 📦  ,
Thank u in advance.

ws = new Sockette(
                "wss://xxxxxxx.execute-api.eu-west-1.amazonaws.com/dev",
                {
                    timeout: 5e3,
                    maxAttempts: 1,
                    onopen: e => console.log("connected:", e),
                    onmessage: e => onMessageReceived(e),
                    onreconnect: e => console.log("Reconnecting...", e),
                    onmaximum: e => console.log("Stop Attempting!", e),
                    onclose: e => console.log("Closed!", e),
                    onerror: e => console.log("Error:", e)
                }
            );

**Comment by swiftmarine** [comment]
fixed by me.

**Comment by chriswebd** [comment]
how did you fixed it?

> fixed by me.
